#pragma once
#ifndef SIGPROCINTERNAL
#define SIGPROCINTERNAL
#endif

enum AUX_PARSING_ERR
{
	UNKNOWN_NAME,
	UNKNOWN_GLOBAL_VARNAME,
	INDEX_OOR,
	CELL_INDEX_OOR,
	TREATING_CELL_WITH_PARENTH,
	RESERVED_AS_BUILT_IN,
};
